name: Local CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ---- Checkout code ----
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---- Set up Python for testing ----
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # ---- Install dependencies and run tests ----
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # ---- Log in to Docker Hub ----
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ---- Build and push Docker image ----
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/phdata-api:latest
